name: pessoa_pensadora
description: Beautify ArquivoPessoa.net

publish_to: 'none'

version: 1.7.1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.1
  html: ^0.15.0
  http: ^1.2.1
  equatable: ^2.0.3
  logger: ^2.2.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.7
  json_serializable: ^6.1.4
  json_annotation: ^4.8.1
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  collection: ^1.18.0
  flutter_slidable: ^4.0.0
  path_provider: ^2.1.3
  flutter_file_dialog: ^3.0.2
  package_info_plus: ^8.0.2
  wakelock_plus: ^1.3.3
  numerus: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0
  test: ^1.24.3
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json_files/all_texts.json
    - assets/images/splash_art.jpg
    # fonts
    - assets/fonts/Roboto/Roboto-Black.ttf
    - assets/fonts/Roboto/Roboto-BlackItalic.ttf
    - assets/fonts/Roboto/Roboto-Bold.ttf
    - assets/fonts/Roboto/Roboto-BoldItalic.ttf
    - assets/fonts/Roboto/Roboto-Italic.ttf
    - assets/fonts/Roboto/Roboto-Light.ttf
    - assets/fonts/Roboto/Roboto-LightItalic.ttf
    - assets/fonts/Roboto/Roboto-Medium.ttf
    - assets/fonts/Roboto/Roboto-MediumItalic.ttf
    - assets/fonts/Roboto/Roboto-Regular.ttf
    - assets/fonts/Roboto/Roboto-Thin.ttf
    - assets/fonts/Roboto/Roboto-ThinItalic.ttf

flutter_launcher_icons:
  image_path: "assets/icon/web.png"
  web:
    generate: true
    image_path: "assets/icon/web.jpeg"
    background_color: "#ffffff"
    theme_color: "#000000"
